name: odoo_repository
description:  Dart package helps to implement data communication between Odoo and dart client with persistance and offline mode
version: 0.5.9
publish_to: none

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  equatable: ^2.0.3
  odoo_rpc: 
    git:
      url: https://github.com/ocean-oo/odoo-rpc-dart.git
      ref: master
  logger: ^2.0.0
  crypto: ^3.0.0

  mutex: ^3.0.0

dev_dependencies:
  lints: '>=3.0.0'
  test: ^1.16.5
  http: ^1.1.0
